// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'collectionmenuitem-fetch'
  | 'menuitem-fetch'
  | 'menutoolsitem-fetchall'
  | 'popwin-cancelhint'
  | 'popwin-cancelled'
  | 'popwin-doicompleted'
  | 'popwin-doifixed'
  | 'popwin-doimissing'
  | 'popwin-fetchfailed'
  | 'popwin-fetching'
  | 'popwin-fetchprogress'
  | 'popwin-fetchsuccess'
  | 'popwin-oaprogress'
  | 'popwin-pdfnotavaliable'
  | 'popwin-unknownerror'
  | 'popwin-unknownerrorclick'
  | 'pref-arxiv'
  | 'pref-autoDownload'
  | 'pref-completedoi'
  | 'pref-email-input'
  | 'pref-help'
  | 'pref-openalex'
  | 'pref-scihub-enabled'
  | 'pref-scihub-input'
  | 'pref-semanticscholar'
  | 'pref-title'
  | 'pref-unpaywall'
  | 'prefs-title';
