// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "firstInstall": boolean;
      "email": string;
      "completeDOI": boolean;
      "openAlex": boolean;
      "unpaywall": boolean;
      "semanticScholar": boolean;
      "arxiv": boolean;
      "scihubEnabled": boolean;
    };
  }
}
